### ISSUE TITLE
Allow easy scheduling of missing jobs from a list of initially scheduled jobs.

### ISSUE THREAD

**Issue by dantp-ai** [yiwan-rl/AlphaEx#3]

**Comment by yiwan-rl** [comment]
One way is to provide a list of range of indices to the submitter., E.g.,

[[1], [3, 5], [8], [100, 105]] 

where [3, 5] means 3, 4, 5.

In this way, the submitter just do

`sbatch --array [1, 3-5, 8, 100-105] submit.sh `

to make the submission
